name: CI
on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  PushooPush:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pushoo Action
        uses: ./.
        with:
          platforms: wecom, dingtalk, bark
          tokens: ${{ secrets.PUSH_TOKEN }}
          content: |
            # Pushoo Action Test
            trigger event: ${{ github.event_name }}
          title: Pushoo Action Test
          options: '{"bark": { "url": "https://github.com/funnyzak" }}'
          debug: false


  Release:
    env:
      DIST_ARCHIVE_NAME: pushoo-action
    runs-on: ubuntu-latest
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org/'
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm install
        npm run build
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: build changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v2.9.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: "config/changelog_configuration.json"
        ignorePreReleases: "false"
    - name: Archive Release
      uses: papeloto/action-zip@v1
      with:
        files: dist/ READEME.md package.json LICENSE action.yml
        recursive: false
        dest: ${{ env.DIST_ARCHIVE_NAME }}.zip
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{steps.build_changelog.outputs.changelog}}
        files:  |
          ${{ env.DIST_ARCHIVE_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
